using System.Collections.Generic;
using UniversityLessonSelectionSystem.Domain.SLAAndHealthMonitor;

namespace UniversityLessonSelectionSystem.Ports.SLAAndHealthMonitor
{
    /// <summary>
    /// Defines a contract for sending, recording, and escalating health or SLA alerts
    /// generated by monitoring services.
    /// 
    /// The implementation may:
    ///  - Persist alerts to a database or telemetry system
    ///  - Send notifications (email, Slack, SMS)
    ///  - Trigger automated incident tickets
    ///  - Record acknowledgements and resolution notes
    /// 
    /// This interface is intentionally simple for mocking and testing purposes.
    /// </summary>
    public interface IAlertGateway
    {
        /// <summary>
        /// Records a single alert in the target system (database, log, or external service).
        /// Called once for each alert emitted by <see cref="Services.SLAAndHealthMonitorService"/>.
        /// </summary>
        /// <param name="alert">The alert to record.</param>
        void Record(Alert alert);

        /// <summary>
        /// Records multiple alerts at once (batch insert or bulk API post).
        /// Implementations may choose to override this for performance.
        /// </summary>
        /// <param name="alerts">List of alerts to record.</param>
        void RecordBatch(IEnumerable<Alert> alerts);

        /// <summary>
        /// Acknowledges an alert when a human or automation confirms it’s being handled.
        /// </summary>
        /// <param name="alertId">The ID or unique identifier of the alert.</param>
        /// <param name="handledBy">Who/what acknowledged it.</param>
        void Acknowledge(string alertId, string handledBy);

        /// <summary>
        /// Escalates a critical alert to an external paging or incident management system.
        /// </summary>
        /// <param name="alert">The alert to escalate.</param>
        void Escalate(Alert alert);
    }
}
